stages:
  - build
  - test
  - push



Build:
  stage: build
  image: alpine:latest
  before_script:
    - apk update
    - apk add --no-cache build-base
    - apk add --no-cache cmake
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -S. -B./build
    - cmake --build ./build --parallel 8
    - ls build/
  artifacts:
    paths:
      - build/



Tests:
  stage: test
  image: alpine:latest
  before_script:
    - apk update
    - apk add --no-cache cmake
  script:
    - ctest --test-dir build
  dependencies:
    - Build



Push:
  stage: push
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_IMAGE_NAME: "$CI_REGISTRY_USER/netlib:latest"
  script:
    - ls
    - ls build
    - ls build/apps
    - docker info
    - docker build -t $CI_REGISTRY_USER .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_USER
  tags:
    - dind
  dependencies:
    - Build
