stages:
  - containerize

Containerize:
  stage: containerize
  image: docker:latest
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
#    DOCKER_TLS_CERTDIR: ""
#    DOCKER_DRIVER: overlay2
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - docker info
  tags:
    - dind
#  dependencies:
#    - Build
