stages:
  - build
  - test
  - deploy

Build:
  stage: build
  image: alpine:latest
  before-script:
    - apk update
    - apk add --no-cache build-base
    - apk add --no-cache cmake
    - apk update
    - apk upgrade
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -S. -B./build
    - cmake --build ./build --parallel 8
  artifacts:
    paths:
      - build/

Tests:
  stage: test
  image: alpine:latest
  before-script:
    - apk update
    - apk add --no-cache cmake
    - apk update
    - apk upgrade
  script:
    - ctest --test-dir build
  dependencies:
    - build

Deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production