stages:
  - containerize

Containerize:
  stage: containerize
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - docker info
  tags:
    - dind
#  dependencies:
#    - Build
